# This is a basic workflow to help you get started with Actions

name: Update 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # Run nightly at 02:00 Swedish time, UTC is -2h from Sweden
    - cron: "00 00 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: actions/checkout@v2
    - name: Update odometer.csv
      run: echo `date +%Y-%m-%dT%H:%M:%S%z`,`voc -u username -p password print odometer` >> odometer.csv
      # TODO: Run nbconvert and update graph
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update of odometer.csv
