name: Daily update of odometer.csv

on:
  schedule:
    # Run nightly at 02:00 Swedish time, UTC is -2h from Sweden
    - cron: "00 00 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update odometer.csv
      run: echo `date -u +%FT%TZ`,`voc -u ${{ secrets.username }} -p ${{ secrets.password }} print odometer` >> odometer.csv
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add new row
